---
- name: Install wordpress on Ubuntu
  hosts: wordpress  # Replace with your EC2 tag or IP address
  become: true

  tasks:
    - name: Update apt cache
      apt:
       update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present
      become: yes

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes
      become: yes

    - name: Install php
      apt:
        name: libapache2-mod-php
        state: present
      become: yes

    - name: php-mysql extension
      apt:
        name: php-mysql
        state: present
      become: yes

    - name: Install zip
      apt:
       name: zip
       state: present
      become: yes

    - name: download wordpress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /var/www/html/

    - name: unzip wordPress 
      ansible.builtin.command:
        cmd: tar -xzvf /var/www/html/wordpress-6.4.1.tar.gz  -C /var/www/html
      become: yes

    - name: add wordpress in configuration file
      command: sed -i 's+/var/www/html+/var/www/html/wordpress+g' /etc/apache2/sites-enabled/000-default.conf
      become: yes

    - name: mv wp-config-sample.php
      command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php

    - name: add database 
      command: sed -i 's+database_name_here+Abhi_db+g' /var/www/html/wordpress/wp-config.php

    - name: add the username
      command: sed -i 's+username_here+Abhi+g' /var/www/html/wordpress/wp-config.php 

    - name: add password
      command: sed -i 's+password_here+password+g' /var/www/html/wordpress/wp-config.php

    - name: Restart apache
      command: systemctl restart apache2
      become: yes

    - name: Install mysql
      apt:
        name: mysql-server
        state: present
      become: yes

    - name: Install mysql-client
      apt: 
        name: mysql-client
        state: present
      become: yes

    - name: Start and mysql service
      service:
        name: mysql
        state: started
        enabled: yes
      become: yes

    - name: start mysql
      command: systemctl start mysql

    - name: enable mysql
      command: systemctl enable mysql

    - name: create database
      command: mysql -e "create database Abhi_db;"

    - name: create user
      command: mysql -e "CREATE USER 'Abhi'@'localhost' IDENTIFIED BY 'password';"

    - name: grant all privileges
      command: mysql -e "GRANT ALL PRIVILEGES ON Abhi_db.* TO 'Abhi'@'localhost';"

    - name: flush privileges
      command: mysql -e "FLUSH PRIVILEGES;"

